Tsotne Meladze - Week 1 - Home Work
bitoid/php-bootcamp-week-1 pull request #3
Opened 2022-05-16 11:15 UTC by tsotneforester

ოთო, გამარჯობა. მეორე დავალებაში CURL მეთოდი მაქვს გამოყენებული, ფუნქციების ფაილში ნახავ, თუმცა მაქვს get_content ის მეთოდითაც მაქვს ფუნქცია შექნილი და ფუნქცისს სახელს თუ გადააკეთებ result და process ფაილში, იმ მეთოდითაც მუშაობს. ერთ php ფაილიანი ვერსიაც მაქვს, მაგრამ რადგან Paginations შევეჭდე, ძალიან გამირთულდა კოდი და დამხმარე ფაილების შემოტანა ვამჯობინე.

2022-05-16 18:15 UTC, tsotneforester commented
ოთო, მოკლედ Your OAuth, GitHub App or personal access token has been revoked, ამიტომ curl აღარ მუშაობდა, ამოვიღე ეგ თოქენი და commit და  push გავაკეთე ხელახლა, რადგან pull ადრეა გამოგზავნილი, ხელახალი არაა საჭირო იმედია...

2022-05-16 19:58 UTC, tsotneforester commented
Minor Fixes

2022-05-16 20:08 UTC, tsotneforester commented
Fix empty folder not commeted/pulled
tip: try to make php code create folder where uploaded images will be stored

2022-05-16 21:23 UTC, otarza requested changes
გადახედე კომენტარებს ამ PR - ზე, იგივე შეცდომები გაქვს დაშვებული: https://github.com/bitoid/php-bootcamp-week-1/pull/2

2022-05-16 21:23 UTC, otarza commented on tsotne_meladze/week1-1/index.php
> +  $stylee = "block";
2 e რას ნიშნავს ცვლადის სახელში?

2022-05-17 08:43 UTC, tsotneforester commented
გეტყოდი, ეგ 2 ee ჩემი ხელწერაა მეთქი, მაგრამ არაა )) მოკლედ ჩავასწორე. რაც შეეხება camelCase, როგორც მივხვდი, OOP-ის დროს ჯობია მაგ სტილის წერის გამოყენება და დამწყებმა  camel_case სტილი გამოიყენოს ჯობია, ხო? რაც შეეხება ცვლადებში HTML ტეგების არსებობას, ზოგადად ვცდილობ ასე არ მოვიქცე, ანუ შენ ამბობ, რომ ცვლადში კი არ უნდა ჩატენო HTML ტაგი + ინფორმაცია, არამედ CSSით უნდა დამალული იყოს ის თაგი და მერე php-ი თან უნდა მიაწოდოს რა ჩაიწეროს იმ თაგში და თან იზრუნოს რომ გამოჩნდეს? მოკლედ ამას ლექციაზე გკითხავ

2022-05-18 15:48 UTC, tsotneforester commented
ოთო, პირველი დავალების კოდი დავვარცხნე, display none -ით დასაბმითების მერე ფორმის გაქრობა და მერე html თაგებიანი სტრინგის დასმა გადავაგდე და empty($_POST) და !empty($_POST) გამოვიყენე, ბეჭდვის ეფექტის js ფაილი მოვაშორე, მდარე მარიაჟობა გამომივიდა ))

2022-05-20 18:42 UTC, tsotneforester commented
ოთო, მეორე დავალებაც ცოტა მოვხოდე. სიმართლე გითხრა, თავიდან ვატენე და ვატენე შიგნით კოდები, მთავარია მუშა და ფუნქციური ყოფილიყო, რეპოს და ფოლოვერების გარდა ორივეს ერთდროულად წამოღება და მერე + pagination, რომელიც პირველად გავაკეთე რეალურად. მაგრმ დღეს რომ ჩავუჯექი კოდს, საერთოდ ვერავერი ვერ გავიგე, თავიდან მომიწია ჩმივე ნაწერის შსწავლა, ამიტომ გავშალე, გავამარტივე, ზედმეტი html სტრინგებიდან ამოვიღე, pagination მოვაშორე და ცოტა გამოიხედა კოდმა თვალებში.

2024-05-20 10:02 UTC, closed without merging